#!/usr/bin/env bash
# transfer a file from our client to a server

# Check if the number of parameters is less than 4
if [ $# -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign the parameters to variables
file=$1
ip=$2
username=$3
ssh_key=$4

# Transfer the file to the server using scp
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file" "$username@$ip:~/"

