#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i '/listen \[::\]:80 default_server;/a \\n\trewrite ^/redirect_me https://twitter.com/jmagolo_jnr permanent;' /etc/nginx/sites-enabled/default

sudo service nginx restart