#!/bin/bash
#check if an argument has been passed
if [ $# -ne 1 ]; then
    echo "Usage: $0 <username>"
    exit 1
fi

# Run the whoami command under the user passed as an argument
su $1 -c "whoami"

